version: "3"

services:
  
  catalog-api:
    image: baseproject/ichoose-catalog-api:latest
    container_name: ichoose-catalog-api
    build:
      context: ../src
      dockerfile: ./services/BaseProject.Catalog.API/Dockerfile
    ports:
      - "4100:4100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:4100
